{
  "name": "mapaset",
  "private": true,
  "version": "0.1.0",
  "packageManager": "pnpm@10.28.0",
  "scripts": {
    "dev:api": "pnpm --filter api dev",
    "dev:web": "pnpm --filter web dev"
  }
}
